language: node_js
node_js:
  - '0.10'
deploy:
  provider: releases
  api_key:
    secure: GNtVxookccXE3FNDWAO3uONRSyvTK6yMhCJlWNhumAQNuQVRyE+Kv3XoWDYONAKVdxTTjdtG4Wu+Lj8onAyNrhg6FRwpGx7uw/M3E1lvE6QRCbPKMS6gl0SpJuqwbu++aEh1ErRbgC8+R+yGf313iJX51tT3GBilPznjmpExZ9k=
  file:
    - "./build/koko-mac.zip"
    - "./build/koko-win-32.zip"
    - "./build/koko-win-64.zip"
  on:
    repo: noraesae/koko
    branch: master
    tags: true
before_deploy:
  - make
  - make package
  - cd build
  - zip -r --symlinks koko-mac Koko.app
  - zip -r koko-win-32 win32
  - zip -r koko-win-64 win64
  - cd ..
