message: ["i"]
command: ["/"]
exit: ["Escape", "Control+c"]
next-tab: ["g>t"]
previous-tab: ["g>T"]
scroll-down: ["j"]
scroll-up: ["k"]
scroll-top: ["g>g"]
scroll-bottom: ["G"]
page-down: ["Control+f"]
page-up: ["Control+b"]
input-history-back: ["ArrowUp"]
input-history-forward: ["ArrowDown"]
autocomplete: ["Tab"]
