message: ["i"]
command: ["/"]
exit: ["esc", "ctrl+c"]
next-tab: ["g>t"]
previous-tab: ["g>T"]
scroll-down: ["j"]
scroll-up: ["k"]
scroll-top: ["g>g"]
scroll-bottom: ["G"]
page-down: ["ctrl+f"]
page-up: ["ctrl+b"]
input-history-back: ["up"]
input-history-forward: ["down"]
autocomplete: ["tab"]
